ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

What follows is a short summary and explanation of the fundamental decisions and solution strategies, that shape our system's architecture

=== Technology
* **Visual Studio Code** as a IDE due to its versatility in developing applications with different programming languages and its compatibility with Git.

* **Docker** to deploy the project, as it allows for the definition of consistent execution environments, ensuring that the application runs the same way in development, testing, and production. Additionally, it supports continuous deployment.

* **GitHub Pages** for deploying the documentation.

* **MongoDB** as a database due to its flexibility when implementing new properties in schemas without having to redo the "tables" every time a new property is added.

* **Azure portal** to deploy the application on the internet due to its ease of configuration, following the instructions provided to developers for deployment, and its potential to install Docker for deploying the Docker containers created in continuous deployment.

=== High-level decomposition
[options="header",cols="1,2,2"]
|===
| *Quality goal* | *Scenario* | *Solution approach*
| Usability | A new user quickly understands how to play and how to ask for basic hints. | Intuitive interface, clear design of the interface for interacting with the predefined hint system.
| Performance | The game loads images and predefined hints in 1-3 seconds. | Image optimization, predefined hint caching.
| Hint Accuracy | Hints provided by the LLM are coherent with user questions and relevant to players progress. | Creation of well-designed *System Instructions* for the LLM, paired with user testing to ensure the overall validity of the results.
| Testability | Developers can run automated tests to verify game functionality. | Modular code design, implementation of unit and integration tests, use of testing frameworks.
|===

=== Approaches to achieve quality objectives

[options="header",cols="1,2,2"]
|===
| *Quality goal* | *Scenario* | *Solution approach*
| Usability | Players on different devices enjoy a consistent experience. | Responsive CSS design, cross-browser and device testing, use of responsive UI frameworks.
| Performance | The game maintains a smooth experience with multiple concurrent players. | Scalable backend with Docker, load balancing, database query optimization.
| Hint Accuracy | Hints provided for the LLM are clear, don't confuse the user or give them the straight answer. | Careful wording of instructions, testing to ensure this scenarios are minimal and fallback mechanisms to stop malfunctions interferencing with the game.
| Testability | Code changes do not introduce regressions. | Continuous integration with automated testing, adequate code coverage, test documentation.
|===

=== Relevant organizational decisions
We have been meeting once a week, although this may change in the future depending on the team's needs to address different topics during development.

In most meetings, if not all, all group members participate, and we discuss opinions on different designs and implementations of the application.

We also have a WhatsApp group as a fast messaging channel.