ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

What follows is a short summary and explanation of the fundamental decisions and solution strategies, that shape our system's architecture

=== Technology
* **Visual Studio Code** as a framework due to its versatility in developing applications with different programming languages and its compatibility with Git.

* **Docker** for deploying the project.

* **GitHub Pages** for deploying the documentation.

=== High-level decomposition

|===
| *Quality goal* | *Scenario* | *Solution approach* | *Link to Details*
| A | A | A | A
| B | B | B | B
| C | C | C | C
|===
=== Approaches to achieve quality objectives
|===
| *Quality goal* | *Scenario* | *Solution approach* | *Link to Details*
| A | A | A | A
| B | B | B | B
| C | C | C | C
|===
=== Relevant organizational decisions
Currently, we have been meeting once a week, although this may change in the future depending on the team's needs to address different topics during development.

In most meetings, if not all, all group members participate, and we discuss opinions on different designs and implementations of the application.

We also have a WhatsApp group as a fast messaging channel.
