ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.


= PLANTILLA DE ESTILO

== Solution Strategy

What follows is a short summary and explanation of the fundamental decisions and solution strategies, that shape our system's architecture

=== Technology
|===
| *Quality goal* | *Scenario* | *Solution approach* | *Link to Details*
| A | A | A | A
| B | B | B | B
| C | C | C | C
|===
=== High-level decomposition 
|===
| *Constraint* | *Description* 
| C1 | D1
| C2 | D2
| C3 | D3
|===
=== Approaches to achieve quality objectives
|===
| *Constraint* | *Description* 
| C1 | D1
| C2 | D2
| C3 | D3
|===
=== Relevant organizational decisions
|===
| *Constraint* | *Description* 
| C1 | D1
| C2 | D2
| C3 | D3
|===
