ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Deployment View

ifdef::arc42help[]
[role="arc42help"]
****
.Content
The deployment view describes:

 1. technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document a deployment view if your software is executed as distributed system with more than one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture only those elements of an infrastructure that are needed to show a deployment of your building blocks. Hardware architects can go beyond that and describe an infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence a system and/or some
cross-cutting concepts. Therefore, there is a need to know the infrastructure.

.Form

Maybe a highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section one can
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than a deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.


.Further Information

See https://docs.arc42.org/section-7/[Deployment View] in the arc42 documentation.

****
endif::arc42help[]

=== Infrastructure

|===
| Element | Description
| _User service_ | Utilized by logged-in users, retrieves their data from the MongoDB database and displays it within the web application.
| _Auth service_ | Ensure user authentication during their initial registration in the game. Collect and securely store all their information in the MongoDB database to facilitate seamless login experiences in subsequent sessions.
| _Gateway service_ | Acts as a central entry point for client requests, routing them to appropriate backend microservices.
| _WebApp_ | Interface for display to the user where the application is housed. Utilizes React as it main form of code and Javascript to interact with the Wikidata external service.
| _LLMService_ | Manages the Language Module and the AI made for the hint system of the application
| _MongoDB_ | The database management system, serves as the backend storage for the application's functionality. It stores user data, generated questions and other game-related information.
|===

[plantuml, format="svg"]
----
@startuml
left to right direction

actor Cliente

node "Azure" {
  node "Ubuntu" {
    node "Docker" {

      node "WebApp" {
        component "React-App"
      }

      node "GatewayService" {
        component "Api"
      }

      node "AuthService" {
        component "AuthService "
      }

      node "UserService" {
        component "UserService "
      }

      node "LLMService" {
        component "LLMService "
      }

      component "Grafana"
      component "Prometheus"
      database "MongoDB"
    }
  }
}

database "Wikidata"
component "LLM-Api"

Cliente --> "WebApp"
Cliente --> "GatewayService"
Cliente --> Grafana

"WebApp" --> "AuthService"
"WebApp" --> "UserService"
"WebApp" --> "GatewayService"
"WebApp" --> "LLMService"

"GatewayService" --> "AuthService"
"GatewayService" --> "UserService"
"GatewayService" --> "LLMService"

"AuthService" --> MongoDB
"UserService" --> MongoDB
"WebApp" --> Wikidata
"LLMService" --> "LLM-Api"

Grafana --> Prometheus
@enduml

----

